DROP DATABASE IF EXISTS Bank;

CREATE DATABASE IF NOT EXISTS Bank;

USE Bank;

CREATE TABLE IF NOT EXISTS Customer (
    id INT AUTO_INCREMENT PRIMARY KEY,
	nif VARCHAR(9) UNIQUE,
	name VARCHAR (100) NOT NULL,
	surname VARCHAR (100) NOT NULL,
	cp INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Account (
	iban VARCHAR (20) PRIMARY KEY,
	owner_id INT NOT NULL,
	balance DOUBLE NOT NULL,
	open_date DATE NOT NULL,
	CONSTRAINT FK_Account_Customer
	FOREIGN KEY (owner_id)
	REFERENCES Customer (id)
	ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Movement (
	id INT AUTO_INCREMENT PRIMARY KEY,
	iban VARCHAR (20) NOT NULL,
	movement_date DATETIME NOT NULL,
	amount DOUBLE  NOT NULL,
	description VARCHAR(200) NOT NULL,
	CONSTRAINT FK_Movement_Account
	FOREIGN KEY (iban)
	REFERENCES Account (iban)
	ON UPDATE CASCADE
    ON DELETE CASCADE
);
